# Generated by Django 3.1.6 on 2021-02-03 15:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Second',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('locations', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('lines', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('polygons', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('mlocations', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('mlines', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('mpolygons', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
