# Generated by Django 3.1.6 on 2021-02-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nitmap', '0002_auto_20210203_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='second',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='second',
            name='mlines',
        ),
        migrations.RemoveField(
            model_name='second',
            name='mlocations',
        ),
        migrations.RemoveField(
            model_name='second',
            name='mpolygons',
        ),
        migrations.RemoveField(
            model_name='second',
            name='polygons',
        ),
    ]
