# Generated by Django 3.1.6 on 2021-02-08 06:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nitmap', '0004_auto_20210208_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lines',
            options={'verbose_name': 'Line'},
        ),
        migrations.AlterModelOptions(
            name='points',
            options={'verbose_name': 'Point'},
        ),
        migrations.AlterModelOptions(
            name='polygons',
            options={'verbose_name': 'Polygon'},
        ),
        migrations.AddField(
            model_name='lines',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18, null=True),
        ),
    ]
