# Generated by Django 3.1.6 on 2021-02-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitmap', '0006_points_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='lines',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='points',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
