# Generated by Django 3.1.6 on 2021-02-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nitmap', '0009_auto_20210209_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygons',
            name='polygons',
        ),
    ]
