# Generated by Django 3.1.6 on 2021-02-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nitmap', '0011_auto_20210212_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='equipment',
        ),
        migrations.AddField(
            model_name='equipment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nitmap.client'),
        ),
    ]
