# Generated by Django 3.1.6 on 2021-02-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitmap', '0012_auto_20210215_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='service_type',
            field=models.CharField(choices=[('Обл.', 'Областной'), ('Респ.', 'Республиканский')], default='Областной', max_length=20),
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
