# Generated by Django 3.1.6 on 2021-02-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitmap', '0013_auto_20210215_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='port_type',
            field=models.CharField(choices=[('Обл.', 'Областной'), ('Респ.', 'Республиканский')], default='Областной', max_length=20),
        ),
        migrations.AlterField(
            model_name='instance',
            name='service_type',
            field=models.CharField(choices=[('БСПД', 'БСПД'), ('Спутник', 'Спутниковый канал'), ('Наземный', 'Наземный канал')], default='БСПД', max_length=20),
        ),
        migrations.DeleteModel(
            name='PortType',
        ),
    ]
