# Generated by Django 3.1.6 on 2021-02-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitmap', '0014_auto_20210215_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
