# Generated by Django 3.1.6 on 2021-02-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitmap', '0015_auto_20210216_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='color',
        ),
        migrations.AddField(
            model_name='points',
            name='with_circle',
            field=models.BooleanField(default=False),
        ),
    ]
