# Generated by Django 3.1.6 on 2021-02-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nitmap', '0016_auto_20210217_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Polygons',
        ),
    ]
