# Generated by Django 3.1.6 on 2021-02-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nitmap', '0018_auto_20210217_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nitmap.clientgroups'),
        ),
    ]
