# Generated by Django 3.1.6 on 2021-02-19 07:06

import colorfield.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nitmap', '0019_client_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='clientgroups',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы клиентов'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.AlterModelOptions(
            name='instance',
            options={'verbose_name': 'Подключение', 'verbose_name_plural': 'Подключения'},
        ),
        migrations.AlterModelOptions(
            name='lines',
            options={'verbose_name': 'Канал', 'verbose_name_plural': 'Каналы'},
        ),
        migrations.AlterModelOptions(
            name='points',
            options={'verbose_name': 'Точка', 'verbose_name_plural': 'Точки'},
        ),
        migrations.AlterModelOptions(
            name='speed',
            options={'verbose_name': 'Скорость каналов', 'verbose_name_plural': 'Скорость каналов'},
        ),
        migrations.RemoveField(
            model_name='points',
            name='name',
        ),
        migrations.AddField(
            model_name='points',
            name='number',
            field=models.CharField(max_length=10, null=True, verbose_name='номер дома/помещения'),
        ),
        migrations.AddField(
            model_name='points',
            name='street',
            field=models.CharField(max_length=100, null=True, verbose_name='улица'),
        ),
        migrations.AlterField(
            model_name='client',
            name='full_name',
            field=models.CharField(default='-', max_length=500, verbose_name='полное наименование'),
        ),
        migrations.AlterField(
            model_name='client',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nitmap.clientgroups', verbose_name='группа'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='краткое наименование'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='контактный телефон'),
        ),
        migrations.AlterField(
            model_name='clientgroups',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nitmap.client', verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='inv_number',
            field=models.CharField(max_length=9, verbose_name='инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=500, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nitmap.client', verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активный'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='is_my',
            field=models.BooleanField(default=True, verbose_name='собственный договор'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='lan',
            field=models.GenericIPAddressField(protocol='IPv4', verbose_name='ip адрес сети'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nitmap.points', verbose_name='точка'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='port_type',
            field=models.CharField(choices=[('Обл.', 'Областной'), ('Респ.', 'Республиканский')], default='Обл.', max_length=20, verbose_name='тип порта'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='service_type',
            field=models.CharField(choices=[('БСПД', 'БСПД'), ('Спутник', 'Спутниковый канал'), ('Наземный', 'ВОЛС/DSL/ADSL/xDSL')], default='Наземный', max_length=20, verbose_name='тип канала'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='speed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nitmap.speed', verbose_name='скорость канала'),
        ),
        migrations.AlterField(
            model_name='lines',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18, null=True, verbose_name='цвет линии'),
        ),
        migrations.AlterField(
            model_name='lines',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='lines',
            name='lines',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='линия'),
        ),
        migrations.AlterField(
            model_name='lines',
            name='name',
            field=models.CharField(max_length=50, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='points',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='доп. информация'),
        ),
        migrations.AlterField(
            model_name='points',
            name='points',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='точка'),
        ),
        migrations.AlterField(
            model_name='points',
            name='with_circle',
            field=models.BooleanField(default=False, verbose_name='с радиусом БСПД'),
        ),
        migrations.AlterField(
            model_name='speed',
            name='name',
            field=models.CharField(max_length=10, verbose_name='скорость канала'),
        ),
    ]
