# Generated by Django 3.1.6 on 2021-02-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitmap', '0022_auto_20210219_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='контактный телефон'),
        ),
    ]
