# Generated by Django 3.1.6 on 2021-02-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nitmap', '0023_auto_20210219_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='instance',
            name='lan_mask',
            field=models.SmallIntegerField(default=24, max_length=2, verbose_name='маска подсети'),
        ),
    ]
